/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Database.GameScore;
import Engine.GameEngine;
import static GUI.Login.gamePlayer;
import java.awt.image.BufferedImage;
import static java.lang.Thread.sleep;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Minodya De Alwis
 */
public class Game extends javax.swing.JFrame {
    
    public static int Score=0;
    
    GameScore AddScore;

    /**
     * Creates new form Game
     */
    GameEngine mathGame = null;
    BufferedImage gameOverview = null;
    static int milliseconds = 0;
    static int seconds = 0;
    static int minutes = 0;
    static int hours = 0;

    static boolean state = true;

    public Game() {
        initComponents();
        showgame(null);
        state = true;

        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    if (state == true) {
                        try {
                            sleep(1);

                            if (milliseconds > 1000) {
                                milliseconds = 0;
                                seconds++;
                            }
                            if (seconds > 60) {
                                milliseconds = 0;
                                seconds = 0;
                                minutes++;
                            }
                            Miliseconds.setText(milliseconds +"");
                            milliseconds++;
                            Seconds.setText(seconds +" : ");
                            Minutes.setText(+ minutes +" : ");
                        } catch (Exception e) {

                        }
                    } else {
                        break;
                    }
                }
            }
        };
        clock.start();

     }

    private void showgame(String gamer) {

        mathGame = new GameEngine(gamer);
        gameOverview = mathGame.nextGame();

        ImageIcon NextImage = new ImageIcon(gameOverview);
        GameArea.setIcon(NextImage);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Minutes = new javax.swing.JLabel();
        Seconds = new javax.swing.JLabel();
        GameArea = new javax.swing.JLabel();
        Miliseconds = new javax.swing.JLabel();
        EnterTheValue = new javax.swing.JLabel();
        AnswerInput = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        BackToHome = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Minutes.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        Minutes.setText("00 :");
        jPanel1.add(Minutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, -1, -1));

        Seconds.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        Seconds.setText("00:");
        jPanel1.add(Seconds, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, -1, -1));
        jPanel1.add(GameArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 810, 350));

        Miliseconds.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        Miliseconds.setText("00");
        jPanel1.add(Miliseconds, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, -1, -1));

        EnterTheValue.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        EnterTheValue.setText("Enter the Value : ");
        jPanel1.add(EnterTheValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        AnswerInput.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        AnswerInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerInputActionPerformed(evt);
            }
        });
        jPanel1.add(AnswerInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        Submit.setBackground(new java.awt.Color(255, 204, 153));
        Submit.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        BackToHome.setBackground(new java.awt.Color(255, 204, 153));
        BackToHome.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        BackToHome.setText("Back to Home");
        BackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToHomeActionPerformed(evt);
            }
        });
        jPanel1.add(BackToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, -1, -1));

        Exit.setBackground(new java.awt.Color(255, 204, 153));
        Exit.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, -1, -1));

        Background.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Background.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToHomeActionPerformed
         this.dispose();
        Home push = new Home();
        push.setVisible(true);        
    
    }//GEN-LAST:event_BackToHomeActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        int answer = Integer.parseInt(AnswerInput.getText());
        boolean correct = mathGame.checkSolution(answer);
        int solution = mathGame.checkSolutionReturn();
        AnswerInput.setText("");
        if (correct) {
            Score = Score + 5;
            this.dispose();
            Score push = new Score();
            push.setVisible(true);
            ImageIcon NextImage = new ImageIcon(gameOverview);
            GameArea.setIcon(NextImage);

        } else {
            JOptionPane.showMessageDialog(this, "Incorrect Value");
            state = false;
            AddScore = new GameScore();
            AddScore.addScore(gamePlayer, Score);
            this.dispose();
            GameOver push = new GameOver();

            push.setVisible(true);

        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void AnswerInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnswerInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
     });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnswerInput;
    private javax.swing.JButton BackToHome;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel EnterTheValue;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel GameArea;
    private javax.swing.JLabel Miliseconds;
    private javax.swing.JLabel Minutes;
    private javax.swing.JLabel Seconds;
    private javax.swing.JButton Submit;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
