/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Database.MySQL;
import Database.UserValidate;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Minodya De Alwis
 */
public class Login extends javax.swing.JFrame {
    
    UserValidate uservalidate;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    
    public static String gamePlayer;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        EmailInput = new javax.swing.JTextField();
        PasswordInput = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        BackToHome = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        Title.setText("Login Form");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        Email.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Email.setText("Email : ");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        Password.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Password.setText("Password : ");
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        EmailInput.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        EmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailInputActionPerformed(evt);
            }
        });
        jPanel1.add(EmailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 260, -1));

        PasswordInput.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jPanel1.add(PasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 260, -1));

        Login.setBackground(new java.awt.Color(255, 204, 153));
        Login.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        Login.setText("Login");
        Login.setBorderPainted(false);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        Exit.setBackground(new java.awt.Color(255, 204, 153));
        Exit.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        Exit.setText("Exit");
        Exit.setBorderPainted(false);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, -1, -1));

        BackToHome.setBackground(new java.awt.Color(255, 204, 153));
        BackToHome.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        BackToHome.setText("Back to Home");
        BackToHome.setBorderPainted(false);
        BackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToHomeActionPerformed(evt);
            }
        });
        jPanel1.add(BackToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        Background.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Background.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailInputActionPerformed

    }//GEN-LAST:event_EmailInputActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        String email = EmailInput.getText();
        char[] password = PasswordInput.getPassword();
        uservalidate = new UserValidate();
        
        if (uservalidate.UserValidate(email, new String(password))) {
            
            JOptionPane.showMessageDialog(this, "Login Successful.");
            gamePlayer = email;
            
            this.dispose();
            Game push = new Game();
            push.setVisible(true);
            
        } else {
            EmailInput.setText("");
            PasswordInput.setText("");
            JOptionPane.showMessageDialog(this, "Login Failed");
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void BackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToHomeActionPerformed
        this.dispose();
        Home push = new Home();
        push.setVisible(true);        
    }//GEN-LAST:event_BackToHomeActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToHome;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Login;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
