/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import Database.MySQL;
import Database.UserAdd;
import User.User;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Minodya De Alwis
 */
public class Register extends javax.swing.JFrame {
    
    UserAdd newuseradd;

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        ConfirmPassword = new javax.swing.JLabel();
        SignUp = new javax.swing.JButton();
        BackToHome = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        NameInput = new javax.swing.JTextField();
        EmailInput = new javax.swing.JTextField();
        PasswordInput = new javax.swing.JPasswordField();
        ConfirmPasswordInput = new javax.swing.JPasswordField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        Title.setText("  Register Form");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        Name.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Name.setText("Name : ");
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        Email.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Email.setText("Email : ");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        Password.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Password.setText("Password : ");
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        ConfirmPassword.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        ConfirmPassword.setText("Confirm Password : ");
        jPanel1.add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        SignUp.setBackground(new java.awt.Color(255, 204, 153));
        SignUp.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        SignUp.setText("Sign Up");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        jPanel1.add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        BackToHome.setBackground(new java.awt.Color(255, 204, 153));
        BackToHome.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        BackToHome.setText("Back to Home");
        BackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToHomeActionPerformed(evt);
            }
        });
        jPanel1.add(BackToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, -1));

        Exit.setBackground(new java.awt.Color(255, 204, 153));
        Exit.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, -1, -1));

        NameInput.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        NameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameInputActionPerformed(evt);
            }
        });
        jPanel1.add(NameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 260, -1));

        EmailInput.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        EmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailInputActionPerformed(evt);
            }
        });
        jPanel1.add(EmailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 270, -1));

        PasswordInput.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordInputActionPerformed(evt);
            }
        });
        jPanel1.add(PasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 270, -1));

        ConfirmPasswordInput.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ConfirmPasswordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordInputActionPerformed(evt);
            }
        });
        jPanel1.add(ConfirmPasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 270, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Background.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameInputActionPerformed

    private void EmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailInputActionPerformed

    private void BackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToHomeActionPerformed
        this.dispose();
        Home push = new Home();
        push.setVisible(true);        
    }//GEN-LAST:event_BackToHomeActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        String name = NameInput.getText();
        String email = EmailInput.getText();
        String reg = "^[A-Za-z0-9+_.-]+@(.+)$";
        Pattern pat = Pattern.compile(reg);
        Matcher match = pat.matcher(email);
        String password = PasswordInput.getText();
        String confirmPassword = ConfirmPasswordInput.getText();
        User user = new User(name, email, password);
        newuseradd = new UserAdd();

        if (name.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the Name");
        } else if (email.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the Email address");
        } else if (!match.matches()) {
            JOptionPane.showMessageDialog(null, "Please enter Valid Email address");
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the Password");
        } else if (password.length() < 8) {
            JOptionPane.showMessageDialog(this, "Enter a password with 8 charactors");
        } else if (confirmPassword.equals("")) {
            JOptionPane.showMessageDialog(this, "Please confirm the password");
        } else if (confirmPassword.length() < 8) {
            JOptionPane.showMessageDialog(this, "Enter a password with 8 charactors");
        } else {
            if (newuseradd.newUserAdd(user.getUserName(), user.getUserEmail(), user.getUserPassword(), confirmPassword)) {
                JOptionPane.showMessageDialog(this, "Registered Succesfully");

                this.dispose();
                Login push = new Login();
                push.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Registration failed");
                PasswordInput.setText("");
                ConfirmPasswordInput.setText("");
            }
        }
    }//GEN-LAST:event_SignUpActionPerformed

    private void PasswordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordInputActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_ExitActionPerformed

    private void ConfirmPasswordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToHome;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel ConfirmPassword;
    private javax.swing.JPasswordField ConfirmPasswordInput;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameInput;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JButton SignUp;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
