/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Database.MySQL;
import static GUI.Login.gamePlayer;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Minodya De Alwis
 */
public class ScoreBoard extends javax.swing.JFrame {
    
    String score;
    String email;
    String str;
    
    /**
     * Creates new form ScoreBoard
     */
    public ScoreBoard() {
        initComponents();
        try {

            MySQL Conne = new MySQL();
            Statement st = Conne.getDBConnection().createStatement();
            ResultSet showData = st.executeQuery("SELECT * FROM gamescore WHERE UserEmail = '" + gamePlayer + "'");

            DefaultTableModel table = (DefaultTableModel) ScoreTable.getModel();
            table.setRowCount(0);
            

             EmailInput.setText(gamePlayer); 

            int count = 0;
            while (showData.next()) {

                score = String.valueOf(showData.getInt("Score"));
                count = count + 1;
                String str = String.valueOf(count);

                String tableArr[] = {str, score};

                table.addRow(tableArr);
            }
        } catch (Exception ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TitleScoreBoard = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        EmailInput = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScoreTable = new javax.swing.JTable();
        PlayAgain = new javax.swing.JButton();
        BackToHome = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleScoreBoard.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        TitleScoreBoard.setText("Hunger Score Board");
        jPanel1.add(TitleScoreBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        Email.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Email.setText("Email : ");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        EmailInput.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanel1.add(EmailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 170, 20));

        ScoreTable.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        ScoreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Round", "Score"
            }
        ));
        jScrollPane1.setViewportView(ScoreTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 370, 230));

        PlayAgain.setBackground(new java.awt.Color(255, 204, 153));
        PlayAgain.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        PlayAgain.setText("Play Again");
        PlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayAgainActionPerformed(evt);
            }
        });
        jPanel1.add(PlayAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, -1));

        BackToHome.setBackground(new java.awt.Color(255, 204, 153));
        BackToHome.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        BackToHome.setText("Back to Home");
        BackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToHomeActionPerformed(evt);
            }
        });
        jPanel1.add(BackToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        Exit.setBackground(new java.awt.Color(255, 204, 153));
        Exit.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Background.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_ExitActionPerformed

    private void PlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayAgainActionPerformed
        this.dispose();
        Game push = new Game();
        push.setVisible(true);        
    }//GEN-LAST:event_PlayAgainActionPerformed

    private void BackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToHomeActionPerformed
        this.dispose();
        Home push = new Home();
        push.setVisible(true);        
    }//GEN-LAST:event_BackToHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreBoard().setVisible(true);
            }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToHome;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel EmailInput;
    private javax.swing.JButton Exit;
    private javax.swing.JButton PlayAgain;
    private javax.swing.JTable ScoreTable;
    private javax.swing.JLabel TitleScoreBoard;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
