/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Engine.GameEngine;
import GUI.Game;
import javax.swing.ImageIcon;

/**
 *
 * @author Minodya De Alwis
 */
public class Score extends javax.swing.JFrame {
    
    int ScoreGet = Game.Score;

    /**
     * Creates new form Score
     */
    public Score() {
        initComponents();
        TotalScore.setText(String.valueOf(ScoreGet));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CorrectIndicator = new javax.swing.JLabel();
        TotalScoreDisplay = new javax.swing.JPanel();
        TotalScore = new javax.swing.JLabel();
        Points = new javax.swing.JLabel();
        PointDisplay = new javax.swing.JLabel();
        Continue = new javax.swing.JButton();
        BackToHome = new javax.swing.JButton();
        ScoreBoard = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CorrectIndicator.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        CorrectIndicator.setForeground(new java.awt.Color(51, 204, 0));
        CorrectIndicator.setText("Your Answer is Correct ✔ Trixie is Happy :)");
        jPanel1.add(CorrectIndicator, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        TotalScore.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        TotalScore.setText("Total Score");

        Points.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Points.setText("Points");

        PointDisplay.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PointDisplay.setText("10");

        javax.swing.GroupLayout TotalScoreDisplayLayout = new javax.swing.GroupLayout(TotalScoreDisplay);
        TotalScoreDisplay.setLayout(TotalScoreDisplayLayout);
        TotalScoreDisplayLayout.setHorizontalGroup(
            TotalScoreDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalScoreDisplayLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(TotalScoreDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalScoreDisplayLayout.createSequentialGroup()
                        .addComponent(PointDisplay)
                        .addGap(51, 51, 51)
                        .addComponent(Points)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalScoreDisplayLayout.createSequentialGroup()
                        .addComponent(TotalScore)
                        .addGap(139, 139, 139))))
        );
        TotalScoreDisplayLayout.setVerticalGroup(
            TotalScoreDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalScoreDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TotalScore)
                .addGap(45, 45, 45)
                .addGroup(TotalScoreDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Points)
                    .addComponent(PointDisplay))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel1.add(TotalScoreDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        Continue.setBackground(new java.awt.Color(255, 204, 153));
        Continue.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        Continue.setText("Continue");
        Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueActionPerformed(evt);
            }
        });
        jPanel1.add(Continue, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        BackToHome.setBackground(new java.awt.Color(255, 204, 153));
        BackToHome.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        BackToHome.setText("Back to Home");
        BackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToHomeActionPerformed(evt);
            }
        });
        jPanel1.add(BackToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        ScoreBoard.setBackground(new java.awt.Color(255, 204, 153));
        ScoreBoard.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        ScoreBoard.setText("Score Board");
        ScoreBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScoreBoardActionPerformed(evt);
            }
        });
        jPanel1.add(ScoreBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        Exit.setBackground(new java.awt.Color(255, 204, 153));
        Exit.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Background.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueActionPerformed
    this.dispose();
    ScoreBoard push = new ScoreBoard();
    push.setVisible(true);        
    }//GEN-LAST:event_ContinueActionPerformed

    private void ScoreBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScoreBoardActionPerformed
        this.dispose();
        ScoreBoard push = new ScoreBoard();
        push.setVisible(true);        
    }//GEN-LAST:event_ScoreBoardActionPerformed

    private void BackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToHomeActionPerformed
        this.dispose();
        Home push = new Home();
        push.setVisible(true);        
    }//GEN-LAST:event_BackToHomeActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Score().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToHome;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Continue;
    private javax.swing.JLabel CorrectIndicator;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel PointDisplay;
    private javax.swing.JLabel Points;
    private javax.swing.JButton ScoreBoard;
    private javax.swing.JLabel TotalScore;
    private javax.swing.JPanel TotalScoreDisplay;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
